apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka01-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka01
  template:
    metadata:
      labels:
        app: kafka01
    spec:
      containers:
      - env:
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka01:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeep01:2181,zookeep02:2181"
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        image: confluentinc/cp-kafka
        name: kafka01
        ports:
        - containerPort: 9092
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-data
      hostname: kafka01
      volumes:
      - name: kafka-data
        hostPath: 
          path: /var/tmp/kafka01/data
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka02-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka02
  template:
    metadata:
      labels:
        app: kafka02
    spec:
      containers:
      - env:
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka02:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeep01:2181,zookeep02:2181"
        - name: KAFKA_BROKER_ID
          value: '2'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        image: confluentinc/cp-kafka
        name: kafka02
        ports:
        - containerPort: 9092
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-data
      hostname: kafka02
      volumes:
      - name: kafka-data
        hostPath: 
          path: /var/tmp/kafka02/data
          type: DirectoryOrCreate