apiVersion: v1
kind: Service
metadata:
  name: kafka01
  labels:
    app: kafka01
spec:
  selector:
    app: kafka01
  ports:
  - name: service
    port: 9092
    protocol: TCP
    targetPort: 9092
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kafka02
  labels:
    app: kafka02
spec:
  selector:
    app: kafka02
  ports:
  - name: service
    port: 9092
    protocol: TCP
    targetPort: 9092
  type: LoadBalancer